services:
  api_server:
    image: flask-example:latest
    pull_policy: never
    environment:
      - TZ=Asia/Shanghai
      - VIRTUAL_HOST=_
      - VIRTUAL_PORT=8000
    healthcheck:
      # 容器基础镜像里有安装 curl。很多 alpine 或 slim 镜像默认不带 curl
      test: test ! -f /tmp/drain && curl -f http://localhost:8000/health
      interval: 5s
      retries: 3
      start_period: 10s
      timeout: 3s
    labels:
      docker-rollout.pre-stop-hook: "touch /tmp/drain && sleep 10"
 
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "5001:80"
      - "9999:9999"
    environment:
      - TZ=Asia/Shanghai
      # 默认会有fallback 503， 如果不需要，确保至少有一个vhost的VIRTUAL_HOST环境变量与DEFAULT_HOST环境变量的值相等。 此外，如果没有任何vhost存在，也会创建fallback server，即使设置了DEFAULT_HOST
      - DEFAULT_HOST=_
    depends_on:
      api_server:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./stream.conf:/etc/nginx/toplevel.conf.d/stream.conf:ro
