# Flask App Configuration
app:
  host: 0.0.0.0
  port: 5000
  debug: false
  api_key: "default_api_key"

# XXL-Job Configuration
xxl:
  enabled: false
  debug: true
  admin:
    baseurl: "http://192.168.71.8:7070/xxl-job-admin/api/"
  executor:
    app_name: "flask-xxl-executor"
    host: "0.0.0.0"
    port: 9999
  access_token: "default_token"